apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::376161510276:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::376161510276:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17DYTEKWZHZUX
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-07T06:12:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "79727"
  uid: e51e8bfa-f739-4ea7-8d3f-884b09996f4f
